version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "80:8000"
    environment:
      - DB_HOST=timescaledb
      - DB_NAME=metrics
      - DB_USER=postgres
      - DB_PASSWORD=password
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - S3_BUCKET=mybucket
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - timescaledb
      - minio

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3data:/data

volumes:
  dbdata:
  s3data:
